// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package weatheragent

import (
	"context"
	"github.com/metaslim/weather/v1/pkg/response"
	"net/http"
	"sync"
)

var (
	lockWeatherAgentMockGetData sync.RWMutex
)

// Ensure, that WeatherAgentMock does implement WeatherAgent.
// If this is not the case, regenerate this file with moq.
var _ WeatherAgent = &WeatherAgentMock{}

// WeatherAgentMock is a mock implementation of WeatherAgent.
//
//     func TestSomethingThatUsesWeatherAgent(t *testing.T) {
//
//         // make and configure a mocked WeatherAgent
//         mockedWeatherAgent := &WeatherAgentMock{
//             GetDataFunc: func(in1 context.Context, in2 string) (response.WeatherResponse, error) {
// 	               panic("mock out the GetData method")
//             },
//         }
//
//         // use mockedWeatherAgent in code that requires WeatherAgent
//         // and then make assertions.
//
//     }
type WeatherAgentMock struct {
	// GetDataFunc mocks the GetData method.
	GetDataFunc func(in1 context.Context, in2 string) (response.WeatherResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetData holds details about calls to the GetData method.
		GetData []struct {
			// In1 is the in1 argument value.
			In1 context.Context
			// In2 is the in2 argument value.
			In2 string
		}
	}
}

// GetData calls GetDataFunc.
func (mock *WeatherAgentMock) GetData(in1 context.Context, in2 string) (response.WeatherResponse, error) {
	if mock.GetDataFunc == nil {
		panic("WeatherAgentMock.GetDataFunc: method is nil but WeatherAgent.GetData was just called")
	}
	callInfo := struct {
		In1 context.Context
		In2 string
	}{
		In1: in1,
		In2: in2,
	}
	lockWeatherAgentMockGetData.Lock()
	mock.calls.GetData = append(mock.calls.GetData, callInfo)
	lockWeatherAgentMockGetData.Unlock()
	return mock.GetDataFunc(in1, in2)
}

// GetDataCalls gets all the calls that were made to GetData.
// Check the length with:
//     len(mockedWeatherAgent.GetDataCalls())
func (mock *WeatherAgentMock) GetDataCalls() []struct {
	In1 context.Context
	In2 string
} {
	var calls []struct {
		In1 context.Context
		In2 string
	}
	lockWeatherAgentMockGetData.RLock()
	calls = mock.calls.GetData
	lockWeatherAgentMockGetData.RUnlock()
	return calls
}

var (
	lockClientMockDo sync.RWMutex
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//     func TestSomethingThatUsesClient(t *testing.T) {
//
//         // make and configure a mocked Client
//         mockedClient := &ClientMock{
//             DoFunc: func(req *http.Request) (*http.Response, error) {
// 	               panic("mock out the Do method")
//             },
//         }
//
//         // use mockedClient in code that requires Client
//         // and then make assertions.
//
//     }
type ClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(req *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Req is the req argument value.
			Req *http.Request
		}
	}
}

// Do calls DoFunc.
func (mock *ClientMock) Do(req *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("ClientMock.DoFunc: method is nil but Client.Do was just called")
	}
	callInfo := struct {
		Req *http.Request
	}{
		Req: req,
	}
	lockClientMockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	lockClientMockDo.Unlock()
	return mock.DoFunc(req)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//     len(mockedClient.DoCalls())
func (mock *ClientMock) DoCalls() []struct {
	Req *http.Request
} {
	var calls []struct {
		Req *http.Request
	}
	lockClientMockDo.RLock()
	calls = mock.calls.Do
	lockClientMockDo.RUnlock()
	return calls
}
